/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import main.FrameMain;
import util.Utility;

/**
 *
 * @author irvin
 */
public class PanelLoading extends javax.swing.JPanel {

    private FrameMain parentFrame;
    /**
     * Creates new form PanelLoading
     */
    public PanelLoading(FrameMain parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        
        // loadingText animation
        new Thread(() -> {
            final String loadingTxt = "Loading";
            String dots = "";
            int counter = 0;
            while (true) {
                if (counter == 0) dots = "";
                dots += ".";
                this.lblLoadingText.setText(loadingTxt + dots);
                counter = (counter + 1) % 3;
                Utility.sleep(500);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoadingGif = new javax.swing.JLabel();
        lblLoadingText = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoadingGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loading.gif"))); // NOI18N
        add(lblLoadingGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 240, 130));

        lblLoadingText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoadingText.setForeground(new java.awt.Color(121, 205, 205));
        lblLoadingText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoadingText.setText("Loading");
        add(lblLoadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 150, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LAB-plain.jpg"))); // NOI18N
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLoadingGif;
    private javax.swing.JLabel lblLoadingText;
    // End of variables declaration//GEN-END:variables
}
