/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JButton;
import main.FrameMain;

/**
 *
 * @author irvin
 */
public class PanelInfo extends javax.swing.JPanel {

    private FrameMain parentFrame;
    /**
     * Creates new form PanelMessage
     */
    public PanelInfo(FrameMain parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
    }

    public PanelInfo(FrameMain parentFrame, String title, String desc) {
        initComponents();
        this.parentFrame = parentFrame;
        this.lblErrorTitle.setText(title);
        this.lblErrorDesc.setText(desc);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErrorIcon = new javax.swing.JLabel();
        lblErrorTitle = new javax.swing.JLabel();
        lblErrorDesc = new javax.swing.JLabel();
        btnOkay = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblErrorIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png"))); // NOI18N
        add(lblErrorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 160, 140));

        lblErrorTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblErrorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorTitle.setText("Who are you?");
        add(lblErrorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 260, 50));

        lblErrorDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblErrorDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorDesc.setText("We can't find your ID in our database.");
        add(lblErrorDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 330, 40));

        btnOkay.setBackground(new java.awt.Color(104, 205, 205));
        btnOkay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOkay.setForeground(new java.awt.Color(255, 255, 255));
        btnOkay.setText("Okay");
        btnOkay.setActionCommand("Okay");
        btnOkay.setBorder(null);
        btnOkay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkayMouseExited(evt);
            }
        });
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });
        add(btnOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 140, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LAB-plain.jpg"))); // NOI18N
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        parentFrame.changeSceneTo(FrameMain.PANEL_SIGN_IN);
    }//GEN-LAST:event_btnOkayActionPerformed

    private void btnOkayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseEntered
        ((JButton)evt.getSource()).setBackground(new Color(80, 180, 180));
    }//GEN-LAST:event_btnOkayMouseEntered

    private void btnOkayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseExited
        ((JButton)evt.getSource()).setBackground(new Color(104, 205, 205));
    }//GEN-LAST:event_btnOkayMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkay;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblErrorDesc;
    private javax.swing.JLabel lblErrorIcon;
    private javax.swing.JLabel lblErrorTitle;
    // End of variables declaration//GEN-END:variables
}
