/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_BrutalForce */

#ifndef _Included_util_BrutalForce
#define _Included_util_BrutalForce
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_BrutalForce
 * Method:    unhook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_BrutalForce_unhook
  (JNIEnv *, jclass);

/*
 * Class:     util_BrutalForce
 * Method:    hook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_BrutalForce_hook
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
